import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "antd/dist/reset.css";
import { ConfigProvider } from "antd";
import enUS from "antd/locale/en_US";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import MainLayout from "@/components/layout/MainLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ConfigProvider locale={enUS} theme={{ token: { colorPrimary: "#1677ff" } }}>
            <ReactQueryProvider>
              <MainLayout>{children}</MainLayout>
            </ReactQueryProvider>
          </ConfigProvider>
        </body>
    </html>
  );
}
